name: aquaculture_monitoring
description: A professional aquaculture monitoring system with simulation capabilities.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  uuid: ^4.1.0
  rxdart: ^0.27.7
  fl_chart: ^0.64.0
  intl: ^0.18.1
  image_picker: ^1.0.4
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

# Override the flutter_local_notifications version to a compatible one
dependency_overrides:
  flutter_local_notifications: 14.1.3+1

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg